ALTER TABLE GE_EVENTO ADD PUNTAJE NUMBER DEFAULT 0;

UPDATE GE_EVENTO SET PUNTAJE = 24 WHERE ID_EVENTO = 1 OR ID_EVENTO = 3;
UPDATE GE_EVENTO SET PUNTAJE = 40 WHERE ID_EVENTO = 2;
UPDATE GE_EVENTO SET PUNTAJE = 64 WHERE ID_EVENTO = 4;
UPDATE GE_EVENTO SET PUNTAJE = 15 WHERE ID_EVENTO = 5;
UPDATE GE_EVENTO SET PUNTAJE = 52 WHERE ID_EVENTO = 6;
UPDATE GE_EVENTO SET PUNTAJE = 20 WHERE ID_EVENTO = 7;
UPDATE GE_EVENTO SET PUNTAJE = 42 WHERE ID_EVENTO = 8;
UPDATE GE_EVENTO SET PUNTAJE = 19 WHERE ID_EVENTO = 9;
UPDATE GE_EVENTO SET PUNTAJE = 38 WHERE ID_EVENTO = 10;