CREATE TABLE PP_ESTADO_TRANSFERENCIA
(
	ID_ESTADO_TRANSFERENCIA NUMBER NOT NULL,
	ID_TRANSFERENCIA NUMBER NOT NULL,
	DESCRIPCION VARCHAR2(100 BYTE) NOT NULL,
	FECHA_REGISTRO DATE NOT NULL,
	ESTADO_ANTERIOR CHAR(1 BYTE) NULL,
	ESTADO_ACTUAL CHAR(1 BYTE) NULL
);

ALTER TABLE PP_ESTADO_TRANSFERENCIA ADD CONSTRAINT PP_EST_TR_PK PRIMARY KEY ( ID_ESTADO_TRANSFERENCIA ) ;