CREATE TABLE LOG_PERSONA
  (
    ID_LOG_PERSONA NUMBER NOT NULL ,
    ID_PERSONA     NUMBER NOT NULL ,
    TELEFONO      VARCHAR2 (20 BYTE) ,
    CORREO        VARCHAR2 (100 BYTE) ,
    USUARIO        VARCHAR2 (50 BYTE) NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL ,
    ACCION         CHAR (1 BYTE) NOT NULL,
    ESTADO         CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE LOG_PERSONA ADD CONSTRAINT LOG_PERSONA_PK PRIMARY KEY ( ID_LOG_PERSONA ) ;

ALTER TABLE LOG_PERSONA ADD CONSTRAINT LOG_PER_FK FOREIGN KEY ( ID_PERSONA ) REFERENCES PERSONA ( ID_PERSONA ) ;
