/* tabla estudios */
CREATE TABLE ESTUDIOS (
	EMPLEADO_DNI NUMBER(8),
	UNIVERSIDAD NUMBER(5),
	AÑO NUMBER(4),
	GRADO VARCHAR2(5),
	ESPECIALIDAD VARCHAR2(20),
	CONSTRAINT PK_ESTUDIOS PRIMARY KEY (EMPLEADO_DNI, AÑO, GRADO),
	CONSTRAINT FK_ESTUDIOS_EMPLEADOS FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS (DNI),CONSTRAINT FK_ESTUDIOS_UNIVERSIDADES FOREIGN KEY (UNIVERSIDAD) REFERENCES UNIVERSIDADES	(UNIV_COD)
);
/* tabla historial_laboral */
CREATE TABLE HISTORIAL_LABORAL (
	EMPLEADO_DNI NUMBER(8),
	TRAB_COD NUMBER(5),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	DPTO_COD NUMBER(5),
	SUPERVISOR_DNI NUMBER(8),
	CONSTRAINT PK_HISTORIAL_LABORAL PRIMARY KEY (EMPLEADO_DNI, FECHA_INICIO),
	CONSTRAINT FK_HLABORAL_EMPLEADOS FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS (DNI),
	CONSTRAINT FK_HLABORAL_TRABAJOS FOREIGN KEY (TRAB_COD) REFERENCES TRABAJOS (TRABAJO_COD),
	CONSTRAINT FK_HLABORAL_DEPARTAMENTOS FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS
	(DPTO_COD),
	CONSTRAINT FK_HLABORAL_SUPERVISOR FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS (DNI),
	CONSTRAINT CK_HLABORAL_FECHAS CHECK (FECHA_FIN IS NULL OR FECHA_INICIO < FECHA_FIN)
);
/* tabla historial_salarial */
CREATE TABLE HISTORIAL_SALARIAL (
	EMPLEADO_DNI NUMBER(8),
	SALARIO NUMBER(5),
	FECHA_COMIENZO DATE,
	FECHA_FIN DATE,
	CONSTRAINT PK_HISTORIAL_SALARIAL PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO),
	CONSTRAINT FK_HISTORIAL_SALARIAL FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS (DNI),
	CONSTRAINT CK_FECHAS CHECK (FECHA_FIN IS NULL OR FECHA_COMIENZO < FECHA_FIN)
);
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';
