CREATE TABLE CLIENTE (
ID_CLIENTE NUMBER PRIMARY KEY, 
APE_PATERNO VARCHAR2(30) NOT NULL, 
APE_MATERNO VARCHAR2(30) NOT NULL, 
NOMBRE VARCHAR2(30) NOT NULL,
SEXO VARCHAR2(1) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL );

CREATE TABLE PRODUCTO ( 
ID_PRODUCTO NUMBER NOT NULL, 
NOMBRE VARCHAR2(30) NOT NULL, 
PRECIO NUMBER NOT NULL,
STOCK NUMBER NOT NULL,
PRIMARY KEY (ID_PRODUCTO));

CREATE TABLE DETALLE_VENTA ( 
ID_DETALLE_VENTA NUMBER NOT NULL,
ID_VENTA NUMBER,  
ID_PRODUCTO NUMBER NOT NULL, 
CANTIDAD NUMBER NOT NULL,
TOTAL NUMBER NOT  NULL,
PRIMARY KEY (ID_DETALLE_VENTA));

CREATE TABLE VENTA (
ID_VENTA NUMBER NOT NULL,
ID_CLIENTE NUMBER NOT NULL, 
FECHA_VENTA DATE NOT NULL, 
PRIMARY KEY (ID_VENTA) );

ALTER TABLE DETALLE_VENTA 
ADD FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA);

ALTER TABLE VENTA 
ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);


