DROP TABLE SRP_ALMACEN CASCADE CONSTRAINTS;

DROP TABLE SRP_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE SRP_DEPARTAMENTO CASCADE CONSTRAINTS;

DROP TABLE SRP_DETALLE_PEDIDO CASCADE CONSTRAINTS;

DROP TABLE SRP_DIRECCION CASCADE CONSTRAINTS;

DROP TABLE SRP_DISTRITO CASCADE CONSTRAINTS;

DROP TABLE SRP_PEDIDO CASCADE CONSTRAINTS;

DROP TABLE SRP_PRODUCTO CASCADE CONSTRAINTS;

DROP TABLE SRP_PRODUCTO_X_ALMACEN CASCADE CONSTRAINTS;

DROP TABLE SRP_PROVINCIA CASCADE CONSTRAINTS;

DROP TABLE SRP_TIPO_CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE SRP_ALMACEN (
    ID_ALMACEN        NUMBER NOT NULL,
    CODIGO_ALMACEN    VARCHAR2(50 BYTE) NOT NULL,
    LOCAL_UBICACION   VARCHAR2(50 BYTE) NOT NULL,
    LATITUD           NUMBER(10,5),
    LONGITUD          NUMBER(10,5),
    ESTADO            NUMBER(1) NOT NULL
);

COMMENT ON COLUMN SRP_ALMACEN.ID_ALMACEN IS
    'IDENTIFICADOR DEL ALMACEN';

COMMENT ON COLUMN SRP_ALMACEN.CODIGO_ALMACEN IS
    'CODIGO DEL ALMACEN';

COMMENT ON COLUMN SRP_ALMACEN.LOCAL_UBICACION IS
    'NOMBRE DEL LOCAL DONDE SE UBICA EL ALMACEN';

COMMENT ON COLUMN SRP_ALMACEN.LATITUD IS
    'VALOR DE LATITUD';

COMMENT ON COLUMN SRP_ALMACEN.LONGITUD IS
    'VALOR DE LONGITUD';

COMMENT ON COLUMN SRP_ALMACEN.ESTADO IS
    '0: INACTIVO, 1: ACTIVO';

ALTER TABLE SRP_ALMACEN ADD CONSTRAINT SRP_ALMACEN_PK PRIMARY KEY ( ID_ALMACEN );

CREATE TABLE SRP_CLIENTE (
    ID_CLIENTE           NUMBER NOT NULL,
    NOMBRES              VARCHAR2(100 BYTE),
    APELLIDOS            VARCHAR2(50 BYTE),
    DOC_IDENTIDAD        VARCHAR2(12 BYTE) NOT NULL,
    TELEFONO             VARCHAR2(10 BYTE),
    CORREO_ELECTRONICO   VARCHAR2(50 BYTE),
    RAZON_SOCIAL         VARCHAR2(150 BYTE),
    NOMBRE_COMERCIAL     VARCHAR2(150 BYTE),
    ID_TIPO_CLIENTE      NUMBER NOT NULL,
    ESTADO               NUMBER(1) NOT NULL
);

COMMENT ON COLUMN SRP_CLIENTE.ID_CLIENTE IS
    'IDENTIFICADOR DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.NOMBRES IS
    'NOMBRES DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.APELLIDOS IS
    'APELLIDOS DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.DOC_IDENTIDAD IS
    'DOCUMENTO DE IDENTIDAD DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.TELEFONO IS
    'TELEFONO DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.CORREO_ELECTRONICO IS
    'CORREO ELECTRONICO DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.RAZON_SOCIAL IS
    'RAZON SOCIAL DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.NOMBRE_COMERCIAL IS
    'NOMBRE COMERCIAL DEL CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.ID_TIPO_CLIENTE IS
    'IDENTIFICADOR DEL TIPO DE CLIENTE. REFERENCIA A LA TABLA SRP_TIPO_CLIENTE';

COMMENT ON COLUMN SRP_CLIENTE.ESTADO IS
    '0: INACTIVO, 1: ACTIVO';

ALTER TABLE SRP_CLIENTE ADD CONSTRAINT SRP_CLIENTE_PK PRIMARY KEY ( ID_CLIENTE );

CREATE TABLE SRP_DEPARTAMENTO (
    ID_DEPARTAMENTO   CHAR(6 BYTE) NOT NULL,
    NOMBRE            VARCHAR2(50 BYTE) NOT NULL
);

COMMENT ON COLUMN SRP_DEPARTAMENTO.ID_DEPARTAMENTO IS
    'IDENTIFICADOR DEL DEPARTAMENTO';

COMMENT ON COLUMN SRP_DEPARTAMENTO.NOMBRE IS
    'NOMBRE DEL DEPARTAMENTO';

ALTER TABLE SRP_DEPARTAMENTO ADD CONSTRAINT SRP_DEPARTAMENTO_PK PRIMARY KEY ( ID_DEPARTAMENTO );

CREATE TABLE SRP_DETALLE_PEDIDO (
    ID_PEDIDO     NUMBER NOT NULL,
    ID_PRODUCTO   NUMBER NOT NULL,
    PRECIO        NUMBER(10,2) NOT NULL,
    CANTIDAD      NUMBER(10,2) NOT NULL,
    ESTADO        NUMBER(1) NOT NULL
)
LOGGING;

COMMENT ON COLUMN SRP_DETALLE_PEDIDO.ID_PEDIDO IS
    'IDENTIFICADOR DEL PEDIDO PADRE';

COMMENT ON COLUMN SRP_DETALLE_PEDIDO.ID_PRODUCTO IS
    'IDENTIFICADOR DEL PRODUCTO QUE FORMA PARTE DEL PEDIDO';

COMMENT ON COLUMN SRP_DETALLE_PEDIDO.PRECIO IS
    'PRECIO (YA INCLIUYE IGV) QUE TIENE CADA UNIDAD DEL PRODUCTO EN ESTE PEDIDO';

COMMENT ON COLUMN SRP_DETALLE_PEDIDO.CANTIDAD IS
    'CANTIDAD DE PRODUCTOS PARA ESTE PEDIDO';

COMMENT ON COLUMN SRP_DETALLE_PEDIDO.ESTADO IS
    '0: ELIMINADO / 1: ACTIVO';

ALTER TABLE SRP_DETALLE_PEDIDO ADD CONSTRAINT SRP_DETALLE_PEDIDO_PK PRIMARY KEY ( ID_PEDIDO,
                                                                                  ID_PRODUCTO );

CREATE TABLE SRP_DIRECCION (
    ID_DIRECCION   NUMBER NOT NULL,
    DIRECCION      VARCHAR2(100) NOT NULL,
    ID_DISTRITO    CHAR(6 BYTE) NOT NULL,
    ID_CLIENTE     NUMBER NOT NULL,
    LATITUD        NUMBER(10,5),
    LONGITUD       NUMBER(10,5),
    ES_PRINCIPAL   NUMBER(1) NOT NULL,
    ESTADO         NUMBER(1) NOT NULL
);

COMMENT ON COLUMN SRP_DIRECCION.ID_DIRECCION IS
    'IDENTIFICADOR DE LA DIRECCION';

COMMENT ON COLUMN SRP_DIRECCION.DIRECCION IS
    'NOMBRE DE LA DIRECCION';

COMMENT ON COLUMN SRP_DIRECCION.ID_DISTRITO IS
    'IDENTIFICADOR DEL DISTRITO';

COMMENT ON COLUMN SRP_DIRECCION.ID_CLIENTE IS
    'IDENTIFICADOR DEL CLIENTE. REFERENCIA A LA TABLA SRP_CLIENTE';

COMMENT ON COLUMN SRP_DIRECCION.LATITUD IS
    'VALOR DE LATITUD';

COMMENT ON COLUMN SRP_DIRECCION.LONGITUD IS
    'VALOR DE LONGITUD';

COMMENT ON COLUMN SRP_DIRECCION.ES_PRINCIPAL IS
    '0: NO, 1: SI';

COMMENT ON COLUMN SRP_DIRECCION.ESTADO IS
    '0: INACTIVO, 1: ACTIVO';

ALTER TABLE SRP_DIRECCION ADD CONSTRAINT SRP_DIRECCION_PK PRIMARY KEY ( ID_DIRECCION );

CREATE TABLE SRP_DISTRITO (
    ID_DISTRITO    CHAR(6 BYTE) NOT NULL,
    NOMBRE         VARCHAR2(50 BYTE) NOT NULL,
    ID_PROVINCIA   CHAR(6 BYTE) NOT NULL
);

COMMENT ON COLUMN SRP_DISTRITO.ID_DISTRITO IS
    'IDENTIFICADOR DEL DISTRITO';

COMMENT ON COLUMN SRP_DISTRITO.NOMBRE IS
    'NOMBRE DEL DISTRITO';

COMMENT ON COLUMN SRP_DISTRITO.ID_PROVINCIA IS
    'IDENTIFICADOR DE LA PROVINCIA. REFERENCIA LA TABLA SRP_PROVINCIA';

ALTER TABLE SRP_DISTRITO ADD CONSTRAINT SRP_DISTRITO_PK PRIMARY KEY ( ID_DISTRITO );

CREATE TABLE SRP_PEDIDO (
    ID_PEDIDO       NUMBER NOT NULL,
    FECHA_PEDIDO    DATE NOT NULL,
    ID_CLIENTE      NUMBER NOT NULL,
    MONTO_TOTAL     NUMBER(10,2) NOT NULL,
    MONTO_IGV       NUMBER(10,2),
    ID_DIRECCION    NUMBER NOT NULL,
    OBSERVACIONES   CLOB,
    ESTADO          NUMBER(1) NOT NULL
)
LOGGING;

COMMENT ON COLUMN SRP_PEDIDO.ID_PEDIDO IS
    'IDENTIFICADOR DEL PEDIDO';

COMMENT ON COLUMN SRP_PEDIDO.FECHA_PEDIDO IS
    'FECHA EN LA QUE SE REALIZO EL PEDIDO';

COMMENT ON COLUMN SRP_PEDIDO.ID_CLIENTE IS
    'IDENTIFICADOR DEL CLIENTE QUE REALIZO EL PEDIDO';

COMMENT ON COLUMN SRP_PEDIDO.MONTO_TOTAL IS
    'MONTO TOTAL DEL PEDIDO (INCLUYE IGV)';

COMMENT ON COLUMN SRP_PEDIDO.MONTO_IGV IS
    'MONTO DEL IGV CORRESPONDIENTE AL PEDIDO';

COMMENT ON COLUMN SRP_PEDIDO.ID_DIRECCION IS
    'IDENTIFICADOR DE LA DIRECCION EN LA QUE SE REALIZARA LA ENTREGA DEL PEDIDO';

COMMENT ON COLUMN SRP_PEDIDO.OBSERVACIONES IS
    'TEXTO CON OBSERVACIONES AL PEDIDO';

COMMENT ON COLUMN SRP_PEDIDO.ESTADO IS
    '0: ELIMINADO / 1: REGISTRADO / 2: RECHAZADO / 3: APROBADO / 4: ENVIO PENDIENTE / 5: CONCRETADO';

ALTER TABLE SRP_PEDIDO ADD CONSTRAINT SRP_PEDIDO_PK PRIMARY KEY ( ID_PEDIDO );

CREATE TABLE SRP_PRODUCTO (
    ID_PRODUCTO       NUMBER NOT NULL,
    CODIGO_PRODUCTO   VARCHAR2(30 BYTE) NOT NULL,
    MODELO            VARCHAR2(100 BYTE),
    PROVEEDOR         VARCHAR2(50 BYTE) NOT NULL,
    PRECIO            NUMBER(10,2) NOT NULL,
    ESTADO            NUMBER(1) NOT NULL
);

COMMENT ON COLUMN SRP_PRODUCTO.ID_PRODUCTO IS
    'IDENTIFICADOR DEL PRODUCTO';

COMMENT ON COLUMN SRP_PRODUCTO.CODIGO_PRODUCTO IS
    'CODIGO DEL PRODUCTO';

COMMENT ON COLUMN SRP_PRODUCTO.MODELO IS
    'MODELO DEL PRODUCTO';

COMMENT ON COLUMN SRP_PRODUCTO.PROVEEDOR IS
    'NOMBRE DEL PROVEEDOR DEL PRODUCTO';

COMMENT ON COLUMN SRP_PRODUCTO.PRECIO IS
    'PRECIO DEL PRODUCTO';

COMMENT ON COLUMN SRP_PRODUCTO.ESTADO IS
    '0: INACTIVO, 1: ACTIVO';

ALTER TABLE SRP_PRODUCTO ADD CONSTRAINT SRP_PRODUCTO_PK PRIMARY KEY ( ID_PRODUCTO );

CREATE TABLE SRP_PRODUCTO_X_ALMACEN (
    ID_PRODUCTO   NUMBER NOT NULL,
    ID_ALMACEN    NUMBER NOT NULL,
    STOCK         NUMBER NOT NULL
);

COMMENT ON COLUMN SRP_PRODUCTO_X_ALMACEN.ID_PRODUCTO IS
    'IDENTIFICADOR DEL PRODUCTO. REFERENCIA A LA TABLA SRP_PRODUCTO';

COMMENT ON COLUMN SRP_PRODUCTO_X_ALMACEN.ID_ALMACEN IS
    'IDENTIFICADOR DEL ALMACEN. REFERENCIA A LA TABLA SRP_ALMACEN';

COMMENT ON COLUMN SRP_PRODUCTO_X_ALMACEN.STOCK IS
    'STOCK DEL PRODUCTO POR ALMACEN';

ALTER TABLE SRP_PRODUCTO_X_ALMACEN ADD CONSTRAINT SRP_PRODUCTO_X_ALMACEN_PK PRIMARY KEY ( ID_PRODUCTO,
                                                                                          ID_ALMACEN );

CREATE TABLE SRP_PROVINCIA (
    ID_PROVINCIA      CHAR(6 BYTE) NOT NULL,
    NOMBRE            VARCHAR2(50 BYTE) NOT NULL,
    ID_DEPARTAMENTO   CHAR(6 BYTE) NOT NULL
);

COMMENT ON COLUMN SRP_PROVINCIA.ID_PROVINCIA IS
    'IDENTIFICADOR DE LA PROVINCIA';

COMMENT ON COLUMN SRP_PROVINCIA.NOMBRE IS
    'NOMBRE DE LA PROVINCIA';

COMMENT ON COLUMN SRP_PROVINCIA.ID_DEPARTAMENTO IS
    'IDENTIFICADOR DEL DEPARTAMENTO. REFERNCIA LA TABLA SRP_DEPARTAMENTO';

ALTER TABLE SRP_PROVINCIA ADD CONSTRAINT SRP_PROVINCIA_PK PRIMARY KEY ( ID_PROVINCIA );

CREATE TABLE SRP_TIPO_CLIENTE (
    ID_TIPO_CLIENTE   NUMBER NOT NULL,
    NOMBRE            VARCHAR2(20 BYTE) NOT NULL,
    ESTADO            NUMBER(1) NOT NULL
);

COMMENT ON COLUMN SRP_TIPO_CLIENTE.ID_TIPO_CLIENTE IS
    'IDENTIFICADOR DEL TIPO DE CLIENTE';

COMMENT ON COLUMN SRP_TIPO_CLIENTE.NOMBRE IS
    'NOMBRE DEL TIPO DE CLIENTE';

COMMENT ON COLUMN SRP_TIPO_CLIENTE.ESTADO IS
    '0: INACTIVO, 1: ACTIVO';

ALTER TABLE SRP_TIPO_CLIENTE ADD CONSTRAINT SRP_TIPO_CLIENTE_PK PRIMARY KEY ( ID_TIPO_CLIENTE );

ALTER TABLE SRP_PRODUCTO_X_ALMACEN
    ADD CONSTRAINT ID_ALMACEN FOREIGN KEY ( ID_ALMACEN )
        REFERENCES SRP_ALMACEN ( ID_ALMACEN )
    NOT DEFERRABLE;

ALTER TABLE SRP_DIRECCION
    ADD CONSTRAINT ID_CLIENTE FOREIGN KEY ( ID_CLIENTE )
        REFERENCES SRP_CLIENTE ( ID_CLIENTE )
    NOT DEFERRABLE;

ALTER TABLE SRP_PROVINCIA
    ADD CONSTRAINT ID_DEPARTAMENTO FOREIGN KEY ( ID_DEPARTAMENTO )
        REFERENCES SRP_DEPARTAMENTO ( ID_DEPARTAMENTO )
    NOT DEFERRABLE;

ALTER TABLE SRP_PRODUCTO_X_ALMACEN
    ADD CONSTRAINT ID_PRODUCTO FOREIGN KEY ( ID_PRODUCTO )
        REFERENCES SRP_PRODUCTO ( ID_PRODUCTO )
    NOT DEFERRABLE;

ALTER TABLE SRP_DISTRITO
    ADD CONSTRAINT ID_PROVINCIA FOREIGN KEY ( ID_PROVINCIA )
        REFERENCES SRP_PROVINCIA ( ID_PROVINCIA )
    NOT DEFERRABLE;

ALTER TABLE SRP_CLIENTE
    ADD CONSTRAINT ID_TIPO_CLIENTE FOREIGN KEY ( ID_TIPO_CLIENTE )
        REFERENCES SRP_TIPO_CLIENTE ( ID_TIPO_CLIENTE )
    NOT DEFERRABLE;

ALTER TABLE SRP_DETALLE_PEDIDO
    ADD CONSTRAINT SRP_DETALLE_PEDIDO_PEDIDO_FK FOREIGN KEY ( ID_PEDIDO )
        REFERENCES SRP_PEDIDO ( ID_PEDIDO )
    NOT DEFERRABLE;

ALTER TABLE SRP_DETALLE_PEDIDO
    ADD CONSTRAINT SRP_DETALLE_PEDIDO_PRODUCTO_FK FOREIGN KEY ( ID_PRODUCTO )
        REFERENCES SRP_PRODUCTO ( ID_PRODUCTO )
    NOT DEFERRABLE;

ALTER TABLE SRP_DIRECCION
    ADD CONSTRAINT SRP_DIRECCION_SRP_DISTRITO_FK FOREIGN KEY ( ID_DISTRITO )
        REFERENCES SRP_DISTRITO ( ID_DISTRITO )
    NOT DEFERRABLE;

ALTER TABLE SRP_PEDIDO
    ADD CONSTRAINT SRP_PEDIDO_SRP_CLIENTE_FK FOREIGN KEY ( ID_CLIENTE )
        REFERENCES SRP_CLIENTE ( ID_CLIENTE )
    NOT DEFERRABLE;
