-- Pregunta 1

-- Estructura
CREATE TABLE SP_INSUMO (
	ID_INSUMO			NUMBER NOT NULL,
	NOMBRE				VARCHAR2(50 BYTE) NOT NULL,
	TIPO_MATERIAL		VARCHAR2(30 BYTE) NOT NULL,
	UNIDAD_DIVISORIA	VARCHAR2(5 BYTE) NOT NULL,
	PRECIO				NUMBER(7,2) NOT NULL,
	STOCK				NUMBER NOT NULL,
	ESTADO				CHAR(6 BYTE) NOT NULL
);
-- Llave primaria
ALTER TABLE SP_INSUMO ADD CONSTRAINT SP_INSUMO_PK PRIMARY KEY ( ID_INSUMO );

-- Pregunta 2

-- Estructura
CREATE TABLE SP_PRODUCTO (
	ID_PRODUCTO			NUMBER NOT NULL,
	NOMBRE				VARCHAR2(50 BYTE) NOT NULL,
	TIPO				NUMBER NOT NULL,
	PRECIO				NUMBER(6,2) NOT NULL,
	ESTADO				CHAR(1 BYTE) NOT NULL
);
-- Llave primaria
ALTER TABLE SP_PRODUCTO ADD CONSTRAINT SP_PRODUCTO_PK PRIMARY KEY ( ID_PRODUCTO );

-- Pregunta 3

-- Estructura
CREATE TABLE SP_MATRIZ_INSUMO (
	ID_MATRIZ			NUMBER NOT NULL,
	ID_PRODUCTO			NUMBER NOT NULL,
	ID_INSUMO			NUMBER NOT NULL,
	CANTIDAD			NUMBER NOT NULL,
	ULTIMA_MODIF		TIMESTAMP NOT NULL
);
-- Llave primaria
ALTER TABLE SP_MATRIZ_INSUMO ADD CONSTRAINT SP_MATRIZ_INSUMO_PK PRIMARY KEY ( ID_MATRIZ );
-- Llave foránea
ALTER TABLE SP_MATRIZ_INSUMO ADD CONSTRAINT MAT_PRO_FK FOREIGN KEY ( ID_PRODUCTO ) REFERENCES SP_PRODUCTO ( ID_PRODUCTO );
ALTER TABLE SP_MATRIZ_INSUMO ADD CONSTRAINT MAT_INS_FK FOREIGN KEY ( ID_INSUMO ) REFERENCES SP_INSUMO ( ID_INSUMO );

-- Pregunta 4
-- Tabla principal SP_ORDEN_COMPRA
-- Estructura
CREATE TABLE SP_ORDEN_COMPRA (
	ID_ORDEN			NUMBER NOT NULL,
	MONTO_TOTAL			NUMBER(6,2) NOT NULL,
	MONTO_IGV			VARCHAR2(20 BYTE) NOT NULL,
	FECHA_REGISTRO		TIMESTAMP NOT NULL,
	FECHA_AUTORIZACION	TIMESTAMP NOT NULL,
	FECHA_ENTREGA		TIMESTAMP NOT NULL,
	ESTADO				CHAR(1 BYTE) NOT NULL
);
-- Llave primaria
ALTER TABLE SP_ORDEN_COMPRA ADD CONSTRAINT SP_ORDEN_COMPRA_PK PRIMARY KEY ( ID_ORDEN );

-- Tabla auxiliar SP_COMPRA_INSUMO
-- Estructura
CREATE TABLE SP_COMPRA_INSUMO (
	ID_COMPRA			NUMBER NOT NULL,
	ID_ORDEN			NUMBER NOT NULL,
	ID_INSUMO			NUMBER NOT NULL,
	CANTIDAD			NUMBER NOT NULL
);
-- Llave primaria
ALTER TABLE SP_COMPRA_INSUMO ADD CONSTRAINT SP_COMPRA_INSUMO_PK PRIMARY KEY ( ID_COMPRA );
-- Llave foránea
ALTER TABLE SP_COMPRA_INSUMO ADD CONSTRAINT COM_ORD_FK FOREIGN KEY ( ID_ORDEN ) REFERENCES SP_ORDEN_COMPRA ( ID_ORDEN );
ALTER TABLE SP_COMPRA_INSUMO ADD CONSTRAINT COM_INS_FK FOREIGN KEY ( ID_INSUMO ) REFERENCES SP_INSUMO ( ID_INSUMO );

-- Pregunta 5

-- Tabla principal SP_ORDEN_PRODUCCION
-- Estructura
CREATE TABLE SP_ORDEN_PRODUCCION (
	ID_ORDEN			NUMBER NOT NULL,
	MOTIVO				CHAR(1 BYTE) NOT NULL,
	FECHA_REGISTRO		TIMESTAMP NOT NULL,
	FECHA_AUTORIZACION	TIMESTAMP NOT NULL,
	FECHA_FIN			TIMESTAMP NOT NULL,
	ESTADO				CHAR(1 BYTE) NOT NULL
);
-- Llave primaria
ALTER TABLE SP_ORDEN_PRODUCCION ADD CONSTRAINT SP_ORDEN_PRODUCCION_PK PRIMARY KEY ( ID_ORDEN );

-- Tabla auxiliar SP_COMPRA_PRODUCTO
-- Estructura
CREATE TABLE SP_COMPRA_PRODUCTO (
	ID_COMPRA			NUMBER NOT NULL,
	ID_ORDEN			NUMBER NOT NULL,
	ID_PRODUCTO			NUMBER NOT NULL,
	UNIDADES			NUMBER NOT NULL,
	MERMA				NUMBER NOT NULL
);
-- Llave primaria
ALTER TABLE SP_COMPRA_PRODUCTO ADD CONSTRAINT SP_COMPRA_PRODUCTO_PK PRIMARY KEY ( ID_COMPRA );
-- Llave foránea
ALTER TABLE SP_COMPRA_PRODUCTO ADD CONSTRAINT PRO_ORD_FK FOREIGN KEY ( ID_ORDEN ) REFERENCES SP_ORDEN_PRODUCCION ( ID_ORDEN );
ALTER TABLE SP_COMPRA_PRODUCTO ADD CONSTRAINT PRO_PRO_FK FOREIGN KEY ( ID_PRODUCTO ) REFERENCES SP_PRODUCTO ( ID_PRODUCTO );
