CREATE TABLE SP_APODERADO
  (
    ID_APODERADO    NUMBER NOT NULL ,
    ID_POSTULANTE   NUMBER NOT NULL ,
    NOMBRE_COMPLETO VARCHAR2 (200 BYTE) NOT NULL ,
    PARENTESCO      CHAR (1 BYTE) NOT NULL ,
    OCUPACION       VARCHAR2 (100 BYTE) ,
    TRABAJO         VARCHAR2 (100 BYTE) ,
    CONTACTO        VARCHAR2 (50 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SP_APODERADO.ID_APODERADO
IS
  'IDENTIFICADOR DEL APODERADO (PK)' ;
  COMMENT ON COLUMN SP_APODERADO.ID_POSTULANTE
IS
  'IDENTIFICADOR DEL POSTULANTE (FK: SP_POSTULANTE)' ;
  COMMENT ON COLUMN SP_APODERADO.NOMBRE_COMPLETO
IS
  'NOMBRE COMPLETO DEL APODERADO' ;
  COMMENT ON COLUMN SP_APODERADO.PARENTESCO
IS
  'PARENTESCO DEL APODERADO CON EL POSTULANTE (P: PADRE, M: MADRE, H: HERMANO(A), F: OTRO FAMILIAR, A: APODERADO)' ;
  COMMENT ON COLUMN SP_APODERADO.OCUPACION
IS
  'OCUPACION DEL APODERADO' ;
  COMMENT ON COLUMN SP_APODERADO.TRABAJO
IS
  'LUGAR DE TRABAJO DEL APODERADO' ;
  COMMENT ON COLUMN SP_APODERADO.CONTACTO
IS
  'INFORMACION DE CONTACTO (TELEFONO) DEL APODERADO' ;
ALTER TABLE SP_APODERADO ADD CONSTRAINT SP_APO_PK PRIMARY KEY ( ID_APODERADO ) ;


CREATE TABLE SP_CENTRO_ESTUDIOS
  (
    ID_CENTRO     NUMBER NOT NULL ,
    NOMBRE        VARCHAR2 (100 BYTE) NOT NULL ,
    DIRECCION     VARCHAR2 (150 BYTE) NOT NULL ,
    TIPO_CENTRO   CHAR (1 BYTE) NOT NULL ,
    TIPO_REGISTRO CHAR (1 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SP_CENTRO_ESTUDIOS.ID_CENTRO
IS
  'IDENTIFICADOR DEL CENTRO DE ESTUDIOS (PK)' ;
  COMMENT ON COLUMN SP_CENTRO_ESTUDIOS.NOMBRE
IS
  'NOMBRE DEL CENTRO DE ESTUDIOS' ;
  COMMENT ON COLUMN SP_CENTRO_ESTUDIOS.DIRECCION
IS
  'DIRECCION DEL CENTRO DE ESTUDIOS' ;
  COMMENT ON COLUMN SP_CENTRO_ESTUDIOS.TIPO_CENTRO
IS
  'TIPO DEL CENTRO DE ESTUDIOS (C: COLEGIO, P: CENTRO PREUNIVERSITARIO)' ;
  COMMENT ON COLUMN SP_CENTRO_ESTUDIOS.TIPO_REGISTRO
IS
  'TIPO DE REGISTRO DEL CENTRO DE ESTUDIOS (A: ACREDITADO POR LA UNIVERSIDAD, M: INGRESADO MANUALMENTE)' ;
ALTER TABLE SP_CENTRO_ESTUDIOS ADD CONSTRAINT SP_CEN_EST_PK PRIMARY KEY ( ID_CENTRO ) ;


CREATE TABLE SP_CONVOCATORIA
  (
    ID_CONVOCATORIA NUMBER NOT NULL ,
    NOMBRE          VARCHAR2 (150 BYTE) NOT NULL ,
    DESCRIPCION     VARCHAR2 (1000 BYTE) ,
    ID_SEMESTRE     NUMBER NOT NULL ,
    FECHA_INICIO    DATE NOT NULL ,
    FECHA_FIN       DATE NOT NULL ,
    ESTADO          CHAR (1 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SP_CONVOCATORIA.ID_CONVOCATORIA
IS
  'IDENTIFICADOR DE LA CONVOCATORIA (PK)' ;
  COMMENT ON COLUMN SP_CONVOCATORIA.NOMBRE
IS
  'NOMBRE DE LA CONVOCATORIA' ;
  COMMENT ON COLUMN SP_CONVOCATORIA.DESCRIPCION
IS
  'DESCRIPCION DE LA CONVOCATORIA' ;
  COMMENT ON COLUMN SP_CONVOCATORIA.ID_SEMESTRE
IS
  'IDENTIFICADOR DEL SEMESTRE (FK: SP_SEMESTRE)' ;
  COMMENT ON COLUMN SP_CONVOCATORIA.FECHA_INICIO
IS
  'FECHA DE INICIO DE LA CONVOCATORIA' ;
  COMMENT ON COLUMN SP_CONVOCATORIA.FECHA_FIN
IS
  'FECHA DE FIN DE LA CONVOCATORIA' ;
  COMMENT ON COLUMN SP_CONVOCATORIA.ESTADO
IS
  'ESTADO DE LA CONVOCATORIA (A: ACTIVO, C: CERRADO)' ;
ALTER TABLE SP_CONVOCATORIA ADD CONSTRAINT SP_CON_PK PRIMARY KEY ( ID_CONVOCATORIA ) ;


CREATE TABLE SP_CONVOCATORIA_MODALIDAD
  (
    ID_CONVOCATORIA NUMBER NOT NULL ,
    ID_MODALIDAD    NUMBER NOT NULL
  ) ;
COMMENT ON COLUMN SP_CONVOCATORIA_MODALIDAD.ID_CONVOCATORIA
IS
  'IDENTIFICADOR DE LA CONVOCATORIA (PK)' ;
  COMMENT ON COLUMN SP_CONVOCATORIA_MODALIDAD.ID_MODALIDAD
IS
  'IDENTIFICADOR DE LA MODALIDAD (PK)' ;
ALTER TABLE SP_CONVOCATORIA_MODALIDAD ADD CONSTRAINT SP_CON_MOD_PK PRIMARY KEY ( ID_CONVOCATORIA, ID_MODALIDAD ) ;


CREATE TABLE SP_CONVOCATORIA_POSTULANTE
  (
    ID_CONVOCATORIA NUMBER NOT NULL ,
    ID_POSTULANTE   NUMBER NOT NULL
  ) ;
COMMENT ON COLUMN SP_CONVOCATORIA_POSTULANTE.ID_CONVOCATORIA
IS
  'IDENTIFICADOR DE LA CONVOCATORIA (PK)' ;
  COMMENT ON COLUMN SP_CONVOCATORIA_POSTULANTE.ID_POSTULANTE
IS
  'IDENTIFICADOR DEL POSTULANTE (PK)' ;
ALTER TABLE SP_CONVOCATORIA_POSTULANTE ADD CONSTRAINT SP_CON_POS_PK PRIMARY KEY ( ID_CONVOCATORIA, ID_POSTULANTE ) ;


CREATE TABLE SP_CUENTA
  (
    ID_CUENTA         NUMBER NOT NULL ,
    BANCO             VARCHAR2 (100 BYTE) NOT NULL ,
    TIPO_CUENTA       CHAR (1 BYTE) NOT NULL ,
    NRO_CUENTA        VARCHAR2 (50 BYTE) NOT NULL ,
    NRO_INTERBANCARIO VARCHAR2 (50 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SP_CUENTA.ID_CUENTA
IS
  'IDENTIFICADOR DE LA CUENTA (PK)' ;
  COMMENT ON COLUMN SP_CUENTA.BANCO
IS
  'NOMBRE DEL BANCO DE LA CUENTA' ;
  COMMENT ON COLUMN SP_CUENTA.TIPO_CUENTA
IS
  'TIPO DE CUENTA BANCARIA (A: CUENTA DE AHORROS, C: CUENTA CORRIENTE)' ;
  COMMENT ON COLUMN SP_CUENTA.NRO_CUENTA
IS
  'NUMERO DE LA CUENTA' ;
  COMMENT ON COLUMN SP_CUENTA.NRO_INTERBANCARIO
IS
  'NUMERO DE CUENTA INTERBANCARIA' ;
ALTER TABLE SP_CUENTA ADD CONSTRAINT SP_CUE_PK PRIMARY KEY ( ID_CUENTA ) ;


CREATE TABLE SP_DOCUMENTO
  (
    ID_DOCUMENTO NUMBER NOT NULL ,
    NOMBRE       VARCHAR2 (100 BYTE) NOT NULL ,
    DESCRIPCION  VARCHAR2 (1000 BYTE) ,
    ID_MODALIDAD NUMBER NOT NULL
  ) ;
COMMENT ON COLUMN SP_DOCUMENTO.ID_DOCUMENTO
IS
  'IDENTIFICADOR DEL DOCUMENTO (PK)' ;
  COMMENT ON COLUMN SP_DOCUMENTO.NOMBRE
IS
  'NOMBRE DEL DOCUMENTO' ;
  COMMENT ON COLUMN SP_DOCUMENTO.DESCRIPCION
IS
  'DESCRIPCION DEL DOCUMENTO' ;
  COMMENT ON COLUMN SP_DOCUMENTO.ID_MODALIDAD
IS
  'IDENTIFICADOR DE LA MODALIDAD (FK: SP_MODALIDAD)' ;
ALTER TABLE SP_DOCUMENTO ADD CONSTRAINT SP_DOC_PK PRIMARY KEY ( ID_DOCUMENTO ) ;


CREATE TABLE SP_DOCUMENTO_POSTULANTE
  (
    ID_DOCUMENTO  NUMBER NOT NULL ,
    ID_POSTULANTE NUMBER NOT NULL ,
    RUTA_ARCHIVO  VARCHAR2 (200 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SP_DOCUMENTO_POSTULANTE.ID_DOCUMENTO
IS
  'IDENTIFICADOR DEL DOCUMENTO (PK)' ;
  COMMENT ON COLUMN SP_DOCUMENTO_POSTULANTE.ID_POSTULANTE
IS
  'IDENTIFICADOR DEL POSTULANTE' ;
  COMMENT ON COLUMN SP_DOCUMENTO_POSTULANTE.RUTA_ARCHIVO
IS
  'RUTA DEL ARCHIVO EN EL REPOSITORIO' ;
ALTER TABLE SP_DOCUMENTO_POSTULANTE ADD CONSTRAINT SP_DOC_POS_PK PRIMARY KEY ( ID_DOCUMENTO, ID_POSTULANTE ) ;


CREATE TABLE SP_ESTADO_PAGO
  (
    ID_ESTADO_PAGO     NUMBER NOT NULL ,
    ID_PAGO            NUMBER NOT NULL ,
    DESCRIPCION        VARCHAR2 (50 BYTE) NOT NULL ,
    FECHA_REGISTRO     DATE NOT NULL ,
    FECHA_MODIFICACION DATE
  ) ;
ALTER TABLE SP_ESTADO_PAGO ADD CONSTRAINT SP_EST_PAG_PK PRIMARY KEY ( ID_ESTADO_PAGO ) ;


CREATE TABLE SP_MODALIDAD
  (
    ID_MODALIDAD NUMBER NOT NULL ,
    NOMBRE       VARCHAR2 (50 BYTE) NOT NULL ,
    DESCRIPCION  VARCHAR2 (1000 BYTE)
  ) ;
COMMENT ON COLUMN SP_MODALIDAD.ID_MODALIDAD
IS
  'IDENTIFICADOR DE LA MODALIDAD (PK)' ;
  COMMENT ON COLUMN SP_MODALIDAD.NOMBRE
IS
  'NOMBRE DE LA MODALIDAD' ;
  COMMENT ON COLUMN SP_MODALIDAD.DESCRIPCION
IS
  'DESCRIPCION DE LA MODALIDAD' ;
ALTER TABLE SP_MODALIDAD ADD CONSTRAINT SP_MOD_PK PRIMARY KEY ( ID_MODALIDAD ) ;


CREATE TABLE SP_PAGO
  (
    ID_PAGO           NUMBER NOT NULL ,
    ID_POSTULANTE     NUMBER NOT NULL ,
    ID_CUENTA         NUMBER NOT NULL ,
    MONTO             NUMBER (10,2) NOT NULL ,
    FECHA_VENCIMIENTO DATE NOT NULL ,
    FECHA_PAGO        DATE ,
    CONCEPTO          VARCHAR2 (100 BYTE)
  ) ;
COMMENT ON COLUMN SP_PAGO.ID_PAGO
IS
  'IDENTIFICADOR DEL PAGO (PK)' ;
  COMMENT ON COLUMN SP_PAGO.ID_POSTULANTE
IS
  'IDENTIFICADOR DEL POSTULANTE (FK: SP_POSTULANTE)' ;
  COMMENT ON COLUMN SP_PAGO.ID_CUENTA
IS
  'IDENTIFICADOR DE LA CUENTA (FK: SP_CUENTA)' ;
  COMMENT ON COLUMN SP_PAGO.MONTO
IS
  'MONTO A PAGAR' ;
  COMMENT ON COLUMN SP_PAGO.FECHA_VENCIMIENTO
IS
  'FECHA DE VENCIMIENTO DEL PAGO' ;
  COMMENT ON COLUMN SP_PAGO.FECHA_PAGO
IS
  'FECHA EN LA QUE SE REALIZA EL PAGO' ;
  COMMENT ON COLUMN SP_PAGO.CONCEPTO
IS
  'CONCEPTO DEL PAGO' ;
ALTER TABLE SP_PAGO ADD CONSTRAINT SP_PAG_PK PRIMARY KEY ( ID_PAGO ) ;


CREATE TABLE SP_POSTULANTE
  (
    ID_POSTULANTE    NUMBER NOT NULL ,
    ID_USUARIO       NUMBER NOT NULL ,
    ID_MODALIDAD     NUMBER NOT NULL ,
    TIPO_DOCUMENTO   CHAR (1 BYTE) NOT NULL ,
    NRO_DOCUMENTO    VARCHAR2 (20 BYTE) NOT NULL ,
    FECHA_NACIMIENTO DATE NOT NULL ,
    TELEFONO         VARCHAR2 (50 BYTE) NOT NULL ,
    DOMICILIO        VARCHAR2 (100 BYTE) NOT NULL ,
    ESTADO           CHAR (1 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SP_POSTULANTE.ID_POSTULANTE
IS
  'IDENTIFICADOR DEL POSTULANTE (PK)' ;
  COMMENT ON COLUMN SP_POSTULANTE.ID_USUARIO
IS
  'IDENTIFICADOR DEL USUARIO (FK: SP_USUARIO)' ;
  COMMENT ON COLUMN SP_POSTULANTE.ID_MODALIDAD
IS
  'IDENTIFICADOR DE LA MODALIDAD DE INGRESO (FK: SP_MODALIDAD)' ;
  COMMENT ON COLUMN SP_POSTULANTE.TIPO_DOCUMENTO
IS
  'D: DNI, C: CARNE DE EXTRANJERIA' ;
  COMMENT ON COLUMN SP_POSTULANTE.NRO_DOCUMENTO
IS
  'NUMERO DE DOCUMENTO DEL POSTULANTE' ;
  COMMENT ON COLUMN SP_POSTULANTE.FECHA_NACIMIENTO
IS
  'FECHA DE NACIMIENTO DEL POSTULANTE' ;
  COMMENT ON COLUMN SP_POSTULANTE.TELEFONO
IS
  'TELEFONO DEL POSTULANTE' ;
  COMMENT ON COLUMN SP_POSTULANTE.DOMICILIO
IS
  'DOMICILIO O DIRECCION DEL POSTULANTE' ;
  COMMENT ON COLUMN SP_POSTULANTE.ESTADO
IS
  'ESTADO DEL POSTULANTE (P: PENDIENTE, A: APROBADO, R: RECHAZADO)' ;
ALTER TABLE SP_POSTULANTE ADD CONSTRAINT SP_POS_PK PRIMARY KEY ( ID_POSTULANTE ) ;


CREATE TABLE SP_POSTULANTE_CENTRO
  (
    ID_POSTULANTE NUMBER NOT NULL ,
    ID_CENTRO     NUMBER NOT NULL ,
    FECHA_INICIO  DATE NOT NULL ,
    FECHA_FIN     DATE NOT NULL
  ) ;
COMMENT ON COLUMN SP_POSTULANTE_CENTRO.ID_POSTULANTE
IS
  'IDENTIFICADOR DEL POSTULANTE (PK)' ;
  COMMENT ON COLUMN SP_POSTULANTE_CENTRO.ID_CENTRO
IS
  'IDENTIFICADOR DEL CENTRO (PK)' ;
  COMMENT ON COLUMN SP_POSTULANTE_CENTRO.FECHA_INICIO
IS
  'FECHA DE INICIO DE LOS ESTUDIOS DEL POSTULANTE EN EL CENTRO' ;
  COMMENT ON COLUMN SP_POSTULANTE_CENTRO.FECHA_FIN
IS
  'FECHA DE FIN  DE LOS ESTUDIOS DEL POSTULANTE EN EL CENTRO' ;
ALTER TABLE SP_POSTULANTE_CENTRO ADD CONSTRAINT SP_POS_CEN_PK PRIMARY KEY ( ID_POSTULANTE, ID_CENTRO ) ;


CREATE TABLE SP_SEMESTRE
  (
    ID_SEMESTRE  NUMBER NOT NULL ,
    NOMBRE       VARCHAR2 (50 BYTE) NOT NULL ,
    FECHA_INICIO DATE NOT NULL ,
    FECHA_FIN    DATE NOT NULL
  ) ;
COMMENT ON COLUMN SP_SEMESTRE.ID_SEMESTRE
IS
  'IDENTIFICADOR DEL SEMESTRE (PK)' ;
  COMMENT ON COLUMN SP_SEMESTRE.NOMBRE
IS
  'NOMBRE DEL SEMESTRE' ;
  COMMENT ON COLUMN SP_SEMESTRE.FECHA_INICIO
IS
  'FECHA DE INICIO DEL SEMESTRE' ;
  COMMENT ON COLUMN SP_SEMESTRE.FECHA_FIN
IS
  'FECHA DE FIN DEL SEMESTRE' ;
ALTER TABLE SP_SEMESTRE ADD CONSTRAINT SP_SEM_PK PRIMARY KEY ( ID_SEMESTRE ) ;


CREATE TABLE SP_USUARIO
  (
    ID_USUARIO  NUMBER NOT NULL ,
    CORREO      VARCHAR2 (150 BYTE) NOT NULL ,
    CONTRASENHA VARCHAR2 (150 BYTE) NOT NULL ,
    NOMBRE      VARCHAR2 (100 BYTE) NOT NULL ,
    AP_PATERNO  VARCHAR2 (50 BYTE) NOT NULL ,
    AP_MATERNO  VARCHAR2 (50 BYTE) NOT NULL ,
    TIPO        CHAR (1 BYTE) NOT NULL ,
    SEXO        CHAR (1 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SP_USUARIO.ID_USUARIO
IS
  'IDENTIFICADOR DEL USUARIO (PK)' ;
  COMMENT ON COLUMN SP_USUARIO.CORREO
IS
  'CORREO ELECTRONICO A USAR COMO CUENTA DE USUARIO' ;
  COMMENT ON COLUMN SP_USUARIO.CONTRASENHA
IS
  'CONTRASENHA DEL USUARIO' ;
  COMMENT ON COLUMN SP_USUARIO.NOMBRE
IS
  'NOMBRES DEL USUARIO' ;
  COMMENT ON COLUMN SP_USUARIO.AP_PATERNO
IS
  'APELLIDO PATERNO DEL USUARIO' ;
  COMMENT ON COLUMN SP_USUARIO.AP_MATERNO
IS
  'APELLIDO MATERNO DEL USUARIO' ;
  COMMENT ON COLUMN SP_USUARIO.TIPO
IS
  'TIPO DEL USUARIO (A: ADMINISTRADOR, P: POSTULANTE, E: EVALUADOR)' ;
  COMMENT ON COLUMN SP_USUARIO.SEXO
IS
  'M: MASCULINO, F: FEMENINO' ;
ALTER TABLE SP_USUARIO ADD CONSTRAINT SP_USU_PK PRIMARY KEY ( ID_USUARIO ) ;


ALTER TABLE SP_APODERADO ADD CONSTRAINT SP_APO_POS_FK FOREIGN KEY ( ID_POSTULANTE ) REFERENCES SP_POSTULANTE ( ID_POSTULANTE ) ;

ALTER TABLE SP_CONVOCATORIA_MODALIDAD ADD CONSTRAINT SP_CON_MOD_CON_FK FOREIGN KEY ( ID_CONVOCATORIA ) REFERENCES SP_CONVOCATORIA ( ID_CONVOCATORIA ) ;

ALTER TABLE SP_CONVOCATORIA_MODALIDAD ADD CONSTRAINT SP_CON_MOD_MOD_FK FOREIGN KEY ( ID_MODALIDAD ) REFERENCES SP_MODALIDAD ( ID_MODALIDAD ) ;

ALTER TABLE SP_CONVOCATORIA_POSTULANTE ADD CONSTRAINT SP_CON_POS_CON_FK FOREIGN KEY ( ID_CONVOCATORIA ) REFERENCES SP_CONVOCATORIA ( ID_CONVOCATORIA ) ;

ALTER TABLE SP_CONVOCATORIA_POSTULANTE ADD CONSTRAINT SP_CON_POS_POS_FK FOREIGN KEY ( ID_POSTULANTE ) REFERENCES SP_POSTULANTE ( ID_POSTULANTE ) ;

ALTER TABLE SP_CONVOCATORIA ADD CONSTRAINT SP_CON_SEM_FK FOREIGN KEY ( ID_SEMESTRE ) REFERENCES SP_SEMESTRE ( ID_SEMESTRE ) ;

ALTER TABLE SP_DOCUMENTO ADD CONSTRAINT SP_DOC_MOD_FK FOREIGN KEY ( ID_MODALIDAD ) REFERENCES SP_MODALIDAD ( ID_MODALIDAD ) ;

ALTER TABLE SP_DOCUMENTO_POSTULANTE ADD CONSTRAINT SP_DOC_POS_DOC_FK FOREIGN KEY ( ID_DOCUMENTO ) REFERENCES SP_DOCUMENTO ( ID_DOCUMENTO ) ;

ALTER TABLE SP_DOCUMENTO_POSTULANTE ADD CONSTRAINT SP_DOC_POS_POS_FK FOREIGN KEY ( ID_POSTULANTE ) REFERENCES SP_POSTULANTE ( ID_POSTULANTE ) ;

ALTER TABLE SP_ESTADO_PAGO ADD CONSTRAINT SP_EST_PAG_PAG_FK FOREIGN KEY ( ID_PAGO ) REFERENCES SP_PAGO ( ID_PAGO ) ;

ALTER TABLE SP_PAGO ADD CONSTRAINT SP_PAG_CUE_FK FOREIGN KEY ( ID_CUENTA ) REFERENCES SP_CUENTA ( ID_CUENTA ) ;

ALTER TABLE SP_PAGO ADD CONSTRAINT SP_PAG_POS_FK FOREIGN KEY ( ID_POSTULANTE ) REFERENCES SP_POSTULANTE ( ID_POSTULANTE ) ;

ALTER TABLE SP_POSTULANTE_CENTRO ADD CONSTRAINT SP_POS_CEN_CEN_FK FOREIGN KEY ( ID_CENTRO ) REFERENCES SP_CENTRO_ESTUDIOS ( ID_CENTRO ) ;

ALTER TABLE SP_POSTULANTE_CENTRO ADD CONSTRAINT SP_POS_CEN_POS_FK FOREIGN KEY ( ID_POSTULANTE ) REFERENCES SP_POSTULANTE ( ID_POSTULANTE ) ;

ALTER TABLE SP_POSTULANTE ADD CONSTRAINT SP_POS_MOD_FK FOREIGN KEY ( ID_MODALIDAD ) REFERENCES SP_MODALIDAD ( ID_MODALIDAD ) ;

ALTER TABLE SP_POSTULANTE ADD CONSTRAINT SP_POS_USU_FK FOREIGN KEY ( ID_USUARIO ) REFERENCES SP_USUARIO ( ID_USUARIO ) ;

