CREATE TABLE LOG_AUDITORIA
  (
    ID_LOG         NUMBER NOT NULL ,
    NOMBRE_TABLA   VARCHAR2 (40 BYTE) NOT NULL ,
    USUARIO        VARCHAR2 (50 BYTE) NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL
  ) ;
ALTER TABLE LOG_AUDITORIA ADD CONSTRAINT LOG_AUDITORIA_PK PRIMARY KEY ( ID_LOG ) ;