CREATE TABLE ASISTENCIA
  (
    ID_ASISTENCIA NUMBER NOT NULL ,
    ID_PERSONA    NUMBER NOT NULL ,
    FECHA_HORA    DATE NOT NULL ,
    ASISTE        CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE ASISTENCIA ADD CONSTRAINT ASISTENCIA_PK PRIMARY KEY ( ID_ASISTENCIA ) ;


CREATE TABLE CARGO
  (
    ID_CARGO      NUMBER NOT NULL ,
    NOMBRE        VARCHAR2 (50 BYTE) NOT NULL ,
    SUELDO_BASICO NUMBER (8,2) NOT NULL ,
    ESTADO        CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE CARGO ADD CONSTRAINT CARGO_PK PRIMARY KEY ( ID_CARGO ) ;

CREATE TABLE PERSONA
  (
    ID_PERSONA         NUMBER NOT NULL ,
    ID_TIPO_DOCUMENTO  NUMBER NOT NULL ,
    NRO_DOCUMENTO      VARCHAR2 (20 BYTE) NOT NULL ,
    NOMBRES            VARCHAR2 (100 BYTE) NOT NULL ,
    TELEFONO           VARCHAR2 (20 BYTE) ,
    CORREO_ELECTRONICO VARCHAR2 (100 BYTE)
  ) ;
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_PK PRIMARY KEY ( ID_PERSONA ) ;


CREATE TABLE PERSONAL
  (
    ID_PERSONAL         NUMBER NOT NULL ,
    ID_PERSONA          NUMBER NOT NULL ,
    ID_CARGO            NUMBER NOT NULL ,
    FECHA_INICIO        DATE NOT NULL ,
    FECHA_FIN           DATE ,
    SUELDO_BASICO       NUMBER (8,2) NOT NULL ,
    SUELDO_BONIFICACION NUMBER (8,2)
  ) ;
ALTER TABLE PERSONAL ADD CONSTRAINT PERSONAL_PK PRIMARY KEY ( ID_PERSONAL ) ;


CREATE TABLE TIPO_DOCUMENTO
  (
    ID_TIPO_DOCUMENTO NUMBER NOT NULL ,
    NOMBRE            VARCHAR2 (50 BYTE) NOT NULL ,
    ESTADO            CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT TIPO_DOCUMENTO_PK PRIMARY KEY ( ID_TIPO_DOCUMENTO ) ;


ALTER TABLE ASISTENCIA ADD CONSTRAINT ASI_PER_FK FOREIGN KEY ( ID_PERSONA ) REFERENCES PERSONA ( ID_PERSONA ) ;

ALTER TABLE PERSONAL ADD CONSTRAINT PEL_CAR_FK FOREIGN KEY ( ID_CARGO ) REFERENCES CARGO ( ID_CARGO ) ;

ALTER TABLE PERSONAL ADD CONSTRAINT PEL_PER_FK FOREIGN KEY ( ID_PERSONA ) REFERENCES PERSONA ( ID_PERSONA ) ;

ALTER TABLE PERSONA ADD CONSTRAINT PER_TIP_DOC_FK FOREIGN KEY ( ID_TIPO_DOCUMENTO ) REFERENCES TIPO_DOCUMENTO ( ID_TIPO_DOCUMENTO ) ;
