DROP TABLE L5_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE L5_DETALLE_VENTA CASCADE CONSTRAINTS;
DROP TABLE L5_LOG_AUDITORIA CASCADE CONSTRAINTS;
DROP TABLE L5_LOG_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE L5_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE L5_VENTA CASCADE CONSTRAINTS;