CREATE TABLE L5_CLIENTE
  (
    ID_CLIENTE       NUMBER NOT NULL ,
    APE_PATERNO      VARCHAR2 (50 BYTE) NOT NULL ,
    APE_MATERNO      VARCHAR2 (50 BYTE) NOT NULL ,
    NOMBRES          VARCHAR2 (100) NOT NULL ,
    SEXO             CHAR (1 BYTE) NOT NULL ,
    FECHA_NACIMIENTO DATE NOT NULL ,
    TELEFONO         VARCHAR2 (20 BYTE) ,
    EMAIL            VARCHAR2 (100 BYTE)
  ) ;
COMMENT ON COLUMN L5_CLIENTE.SEXO
IS
  'M: MASCULINO, F: FEMENINO' ;
ALTER TABLE L5_CLIENTE ADD CONSTRAINT L5_CLI_PK PRIMARY KEY ( ID_CLIENTE ) ;


CREATE TABLE L5_DETALLE_VENTA
  (
    ID_DETALLE_VENTA NUMBER NOT NULL ,
    ID_VENTA         NUMBER NOT NULL ,
    ID_PRODUCTO      NUMBER NOT NULL ,
    CANTIDAD         NUMBER NOT NULL ,
    SUB_TOTAL        NUMBER (10,2) NOT NULL ,
    IGV              NUMBER (10,2) NOT NULL ,
    TOTAL            NUMBER (10,2) NOT NULL
  ) ;
ALTER TABLE L5_DETALLE_VENTA ADD CONSTRAINT L5_DET_VEN_PK PRIMARY KEY ( ID_DETALLE_VENTA ) ;


CREATE TABLE L5_LOG_AUDITORIA
  (
    ID_LOG         NUMBER NOT NULL ,
    NOMBRE_TABLA   VARCHAR2 (50 BYTE) NOT NULL ,
    USUARIO        VARCHAR2 (50 BYTE) NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL
  ) ;
ALTER TABLE L5_LOG_AUDITORIA ADD CONSTRAINT L5_LOG_AUD_PK PRIMARY KEY ( ID_LOG ) ;


CREATE TABLE L5_LOG_CLIENTE
  (
    ID_LOG_CLIENTE NUMBER NOT NULL ,
    ID_CLIENTE     NUMBER NOT NULL ,
    TELEFONO_ANT   VARCHAR2 (20 BYTE) ,
    TELEFONO_NUE   VARCHAR2 (20 BYTE) ,
    EMAIL_ANT      VARCHAR2 (100 BYTE) ,
    EMAIL_NUE      VARCHAR2 (100 BYTE) ,
    USUARIO        VARCHAR2 (50 BYTE) NOT NULL ,
    FECHA_REGISTRO DATE NOT NULL ,
    ACCION         CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE L5_LOG_CLIENTE ADD CONSTRAINT L5_LOG_CLI_PK PRIMARY KEY ( ID_LOG_CLIENTE ) ;


CREATE TABLE L5_PRODUCTO
  (
    ID_PRODUCTO NUMBER NOT NULL ,
    NOMBRE      VARCHAR2 (50 BYTE) NOT NULL ,
    PRECIO      NUMBER (10,2) NOT NULL ,
    STOCK       NUMBER NOT NULL
  ) ;
ALTER TABLE L5_PRODUCTO ADD CONSTRAINT L5_PRO_PK PRIMARY KEY ( ID_PRODUCTO ) ;


CREATE TABLE L5_VENTA
  (
    ID_VENTA      NUMBER NOT NULL ,
    ID_CLIENTE    NUMBER NOT NULL ,
    FECHA_VENTA   DATE NOT NULL ,
    FECHA_ENTREGA DATE ,
    SUB_TOTAL     NUMBER (10,2) NOT NULL ,
    IGV           NUMBER (10,2) NOT NULL ,
    TOTAL         NUMBER (10,2) NOT NULL
  ) ;
ALTER TABLE L5_VENTA ADD CONSTRAINT L5_VEN_PK PRIMARY KEY ( ID_VENTA ) ;


ALTER TABLE L5_DETALLE_VENTA ADD CONSTRAINT L5_DET_VEN_PRO_FK FOREIGN KEY ( ID_PRODUCTO ) REFERENCES L5_PRODUCTO ( ID_PRODUCTO ) ;

ALTER TABLE L5_DETALLE_VENTA ADD CONSTRAINT L5_DET_VEN_VEN_FK FOREIGN KEY ( ID_VENTA ) REFERENCES L5_VENTA ( ID_VENTA ) ;

ALTER TABLE L5_VENTA ADD CONSTRAINT L5_VEN_CLI_FK FOREIGN KEY ( ID_CLIENTE ) REFERENCES L5_CLIENTE ( ID_CLIENTE ) ;
