-- INF246 - BASES DE DATOS
-- 3ra. Práctica (Tipo B)
-- PARTE CALIFICADA
--
-- Estructura de la Base de Datos

CREATE TABLE GE_CATEGORIA_EVENTO
  (
    ID_CATEGORIA_EVENTO NUMBER NOT NULL ,
    NOMBRE_CATEGORIA    VARCHAR2 (50 BYTE) NOT NULL ,
    ESTADO              CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE GE_CATEGORIA_EVENTO ADD CONSTRAINT GE_CATEGORIA_EVENTO_PK PRIMARY KEY ( ID_CATEGORIA_EVENTO ) ;


CREATE TABLE GE_DEPARTAMENTO
  (
    ID_DEPARTAMENTO CHAR (6 BYTE) NOT NULL ,
    NOMBRE          VARCHAR2 (50 BYTE) NOT NULL
  ) ;
ALTER TABLE GE_DEPARTAMENTO ADD CONSTRAINT GE_DEPARTAMENTO_PK PRIMARY KEY ( ID_DEPARTAMENTO ) ;


CREATE TABLE GE_DISTRITO
  (
    ID_DISTRITO  CHAR (6 BYTE) NOT NULL ,
    NOMBRE       VARCHAR2 (50 BYTE) NOT NULL ,
    ID_PROVINCIA CHAR (6 BYTE) NOT NULL
  ) ;
ALTER TABLE GE_DISTRITO ADD CONSTRAINT GE_DISTRITO_PK PRIMARY KEY ( ID_DISTRITO ) ;


CREATE TABLE GE_EVENTO
  (
    ID_EVENTO         NUMBER NOT NULL ,
    NOMBRE            VARCHAR2 (100 BYTE) NOT NULL ,
    TEMA              VARCHAR2 (200 BYTE) NOT NULL ,
    OBJETIVO          VARCHAR2 (1000 BYTE) NOT NULL ,
    FECHA_HORA_INICIO DATE NOT NULL ,
    FECHA_HORA_FIN    DATE ,
    UBIGEO            CHAR (6 BYTE) NOT NULL ,
    LATITUD           VARCHAR2 (50 BYTE) ,
    LONGITUD          VARCHAR2 (50 BYTE) ,
    DIRECCION         VARCHAR2 (100 BYTE) NOT NULL ,
    ID_TIPO_EVENTO    NUMBER NOT NULL ,
    ID_SECTOR         NUMBER NOT NULL ,
    AFORO             NUMBER ,
    VIRTUAL           CHAR (1 BYTE) ,
    ENLACE            VARCHAR2 (200 BYTE) ,
    ID_RESPONSABLE    NUMBER NOT NULL ,
    CARGO_RESPONSABLE VARCHAR2 (50) NOT NULL ,
    ESTADO            CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE GE_EVENTO ADD CONSTRAINT GE_EVENTO_PK PRIMARY KEY ( ID_EVENTO ) ;


CREATE TABLE GE_PERSONA
  (
    ID_PERSONA         NUMBER NOT NULL ,
    NOMBRES            VARCHAR2 (50 BYTE) NOT NULL ,
    APELLIDOS          VARCHAR2 (50 BYTE) NOT NULL ,
    TIPO_DOCUMENTO     CHAR (1 BYTE) NOT NULL ,
    NRO_DOCUMENTO      VARCHAR2 (20 BYTE) NOT NULL ,
    TELEFONO           VARCHAR2 (50 BYTE) NOT NULL ,
    CORREO_ELECTRONICO VARCHAR2 (100 BYTE) ,
    ESTADO             CHAR (1 BYTE) NOT NULL ,
	FECHA_NACIMIENTO   DATE NOT NULL
  ) ;
ALTER TABLE GE_PERSONA ADD CONSTRAINT GE_PERSONA_PK PRIMARY KEY ( ID_PERSONA ) ;


CREATE TABLE GE_PERSONA_EVENTO
  (
    ID_EVENTO  NUMBER NOT NULL ,
    ID_PERSONA NUMBER NOT NULL ,
    ASISTENCIA CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE GE_PERSONA_EVENTO ADD CONSTRAINT GE_PARTICIPANTE_PK PRIMARY KEY ( ID_EVENTO, ID_PERSONA ) ;


CREATE TABLE GE_PROVINCIA
  (
    ID_PROVINCIA    CHAR (6 BYTE) NOT NULL ,
    NOMBRE          VARCHAR2 (50 BYTE) NOT NULL ,
    ID_DEPARTAMENTO CHAR (6 BYTE) NOT NULL
  ) ;
ALTER TABLE GE_PROVINCIA ADD CONSTRAINT GE_PROVINCIA_PK PRIMARY KEY ( ID_PROVINCIA ) ;


CREATE TABLE GE_RESULTADO
  (
    ID_RESULTADO      NUMBER NOT NULL ,
    ID_EVENTO         NUMBER NOT NULL ,
    FECHA_HORA_INICIO DATE NOT NULL ,
    FECHA_HORA_FIN    DATE ,
    LOGROS            VARCHAR2 (2000 BYTE) ,
    ACCIONES          VARCHAR2 (2000 BYTE) ,
    COMENTARIOS       VARCHAR2 (2000 BYTE)
  ) ;
ALTER TABLE GE_RESULTADO ADD CONSTRAINT GE_RESULTADO_PK PRIMARY KEY ( ID_RESULTADO ) ;


CREATE TABLE GE_SECTOR
  (
    ID_SECTOR     NUMBER NOT NULL ,
    NOMBRE_SECTOR VARCHAR2 (50 BYTE) NOT NULL ,
    SIGLAS        CHAR (3 BYTE) NOT NULL ,
    ESTADO        CHAR (1 BYTE) NOT NULL
  ) ;
ALTER TABLE GE_SECTOR ADD CONSTRAINT GE_SECTOR_PK PRIMARY KEY ( ID_SECTOR ) ;


CREATE TABLE GE_TIPO_EVENTO
  (
    ID_TIPO_EVENTO      NUMBER NOT NULL ,
    NOMBRE_TIPO         VARCHAR2 (50 BYTE) NOT NULL ,
    ESTADO              CHAR (1 BYTE) NOT NULL ,
    ID_CATEGORIA_EVENTO NUMBER NOT NULL
  ) ;
ALTER TABLE GE_TIPO_EVENTO ADD CONSTRAINT GE_TIPO_EVENTO_PK PRIMARY KEY ( ID_TIPO_EVENTO ) ;

CREATE TABLE GE_ARCHIVO
  (
    ID_ARCHIVO         NUMBER NOT NULL ,
    NOMBRE             VARCHAR2 (100 BYTE) NULL ,
	TIPO			   VARCHAR2 (50 BYTE) NOT NULL ,
    RUTA               VARCHAR2 (200 BYTE) NOT NULL ,
	ID_EVENTO 		   NUMBER NOT NULL ,
	TAMANO			   NUMBER NOT NULL
  ) ;
ALTER TABLE GE_ARCHIVO ADD CONSTRAINT GE_ARCHIVO_PK PRIMARY KEY ( ID_ARCHIVO );

/* Llaves foráneas */

ALTER TABLE GE_DISTRITO ADD CONSTRAINT DIS_PRO_FK FOREIGN KEY ( ID_PROVINCIA ) REFERENCES GE_PROVINCIA ( ID_PROVINCIA ) ;

ALTER TABLE GE_EVENTO ADD CONSTRAINT EVE_DIS_FK FOREIGN KEY ( UBIGEO ) REFERENCES GE_DISTRITO ( ID_DISTRITO ) ;
ALTER TABLE GE_EVENTO ADD CONSTRAINT EVE_RES_FK FOREIGN KEY ( ID_RESPONSABLE ) REFERENCES GE_PERSONA ( ID_PERSONA ) ;
ALTER TABLE GE_EVENTO ADD CONSTRAINT EVE_SEC_FK FOREIGN KEY ( ID_SECTOR ) REFERENCES GE_SECTOR ( ID_SECTOR ) ;
ALTER TABLE GE_EVENTO ADD CONSTRAINT EVE_TEV_FK FOREIGN KEY ( ID_TIPO_EVENTO ) REFERENCES GE_TIPO_EVENTO ( ID_TIPO_EVENTO ) ;

ALTER TABLE GE_PERSONA_EVENTO ADD CONSTRAINT PAR_EVE_FK FOREIGN KEY ( ID_EVENTO ) REFERENCES GE_EVENTO ( ID_EVENTO ) ;
ALTER TABLE GE_PERSONA_EVENTO ADD CONSTRAINT PAR_PER_FK FOREIGN KEY ( ID_PERSONA ) REFERENCES GE_PERSONA ( ID_PERSONA ) ;

ALTER TABLE GE_PROVINCIA ADD CONSTRAINT PRO_DEP_FK FOREIGN KEY ( ID_DEPARTAMENTO ) REFERENCES GE_DEPARTAMENTO ( ID_DEPARTAMENTO ) ;

ALTER TABLE GE_RESULTADO ADD CONSTRAINT RES_EVE_FK FOREIGN KEY ( ID_EVENTO ) REFERENCES GE_EVENTO ( ID_EVENTO ) ;

ALTER TABLE GE_TIPO_EVENTO ADD CONSTRAINT TEV_CEV_FK FOREIGN KEY ( ID_CATEGORIA_EVENTO ) REFERENCES GE_CATEGORIA_EVENTO ( ID_CATEGORIA_EVENTO ) ;

ALTER TABLE GE_ARCHIVO ADD CONSTRAINT ARC_EVE_FK FOREIGN KEY(ID_EVENTO) REFERENCES GE_EVENTO(ID_EVENTO); 

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
