INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(1, 'Fresa', 'Sabor fresa', 6.0, 'A');
INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(2, 'Chocolate', 'Sabor chocolate', 12.0, 'A');
INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(3, 'Vainilla', 'Sabor vainilla', 4.2, 'A');
INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(4, 'Capucchino', 'Sabor capucchino', 12.0, 'A');
INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(5, 'Frutas secas', 'Sabor frutas secas', 3.0, 'A');
INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(6, 'Mango', 'Sabor mango', 0.6, 'A');
INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(7, 'Coco', 'Sabor coco', 0.0, 'D');
INSERT INTO HE_SABOR (ID_SABOR, NOMBRE, DESCRIPCION, STOCK, ESTADO) VALUES
(8, 'Manjar blanco', 'Sabor manjar blanco', 0.0, 'D');
-- 1 2 3 4 6
INSERT INTO HE_ORDEN_PRODUCCION (ID_ORDEN_PRODUCCION, ID_SABOR, CANTIDAD, FECHA_HORA_REGISTRO, FECHA_HORA_TERM_PLANIF, FECHA_HORA_TERM_REAL, ESTADO) VALUES
(1, 1, 6.6, TO_DATE('25/01/2023', 'DD/MM/YYYY'), TO_DATE('26/01/2023', 'DD/MM/YYYY'), NULL, 'S');
INSERT INTO HE_ORDEN_PRODUCCION (ID_ORDEN_PRODUCCION, ID_SABOR, CANTIDAD, FECHA_HORA_REGISTRO, FECHA_HORA_TERM_PLANIF, FECHA_HORA_TERM_REAL, ESTADO) VALUES
(2, 2, 12.0, TO_DATE('25/01/2023', 'DD/MM/YYYY'), TO_DATE('26/01/2023', 'DD/MM/YYYY'), NULL, 'S');
INSERT INTO HE_ORDEN_PRODUCCION (ID_ORDEN_PRODUCCION, ID_SABOR, CANTIDAD, FECHA_HORA_REGISTRO, FECHA_HORA_TERM_PLANIF, FECHA_HORA_TERM_REAL, ESTADO) VALUES
(3, 3, 18.0, TO_DATE('26/01/2023', 'DD/MM/YYYY'), TO_DATE('28/01/2023', 'DD/MM/YYYY'), NULL, 'S');
INSERT INTO HE_ORDEN_PRODUCCION (ID_ORDEN_PRODUCCION, ID_SABOR, CANTIDAD, FECHA_HORA_REGISTRO, FECHA_HORA_TERM_PLANIF, FECHA_HORA_TERM_REAL, ESTADO) VALUES
(4, 4, 3.0, TO_DATE('26/01/2023', 'DD/MM/YYYY'), TO_DATE('28/01/2023', 'DD/MM/YYYY'), NULL, 'S');
INSERT INTO HE_ORDEN_PRODUCCION (ID_ORDEN_PRODUCCION, ID_SABOR, CANTIDAD, FECHA_HORA_REGISTRO, FECHA_HORA_TERM_PLANIF, FECHA_HORA_TERM_REAL, ESTADO) VALUES
(5, 6, 4.8, TO_DATE('26/01/2023', 'DD/MM/YYYY'), TO_DATE('28/01/2023', 'DD/MM/YYYY'), NULL, 'S');

INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(1, 'Cono 1 bola', 'Cono con 1 bola', 1, 1.5, 'A');
INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(2, 'Cono 2 bolas', 'Cono con 2 bolas', 2, 3.0, 'A');
INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(3, 'Cono 3 bolas', 'Cono con 3 bolas', 3, 4.5, 'A');
INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(4, 'Vaso 1 bola', 'Vaso con 1 bola', 1, 1.0, 'A');
INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(5, 'Vaso 2 bolas', 'Vaso con 2 bolas', 2, 2.0, 'A');
INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(6, 'Vaso 3 bolas', 'Vaso con 3 bolas', 3, 3.0, 'A');
INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(7, 'Oblea', '3 bolas de helado en una oblea', 3, 6.0, 'A');
INSERT INTO HE_POSTRE (ID_POSTRE, NOMBRE, DESCRIPCION, NUMERO_BOLAS, PRECIO, ESTADO) VALUES
(8, 'Crepe', 'Crepe con 2 bolas de helado', 2, 5.0, 'A');

INSERT INTO HE_COMPLEMENTO_POSTRE (ID_COMPLEMENTO_POSTRE, NOMBRE, DESCRIPCION, STOCK, PRECIO) VALUES
(1, 'Fudge', 'Dulce de azúcar con chocolate para cobertura', 20, 0.5);
INSERT INTO HE_COMPLEMENTO_POSTRE (ID_COMPLEMENTO_POSTRE, NOMBRE, DESCRIPCION, STOCK, PRECIO) VALUES
(2, 'Rollito de vainilla', 'Galleta dulce en forma de rollo de vainilla', 40, 1.0);
INSERT INTO HE_COMPLEMENTO_POSTRE (ID_COMPLEMENTO_POSTRE, NOMBRE, DESCRIPCION, STOCK, PRECIO) VALUES
(3, 'Lentejas Donofrio', 'Chocolares cubiertos con caramelo.', 30, 1.0);

